spring.application.name=finmate-api
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/finmate
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
server.port=8080
server.servlet.context-path=/api

# Exchange Rate API (exchangeratesapi.io)
exchange-rate.api-url=https://api.exchangeratesapi.io/v1/latest
exchange-rate.access-key=${EXCHANGE_RATE_ACCESS_KEY:3863aa3906f38534cc2ff2db4524540f}
exchange-rate.symbols=USD,VND,JPY,KRW,HKD,CNY